DROP TABLE IF EXISTS "workoutTbl";
CREATE TABLE "workoutTbl" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "type" VARCHAR, "difficulty" VARCHAR, "duration" VARCHAR, "description" VARCHAR);
INSERT INTO "workoutTbl" VALUES(1,'Bike','Easy','>60','bike 115 min steady and 35 min up-tempo');
INSERT INTO "workoutTbl" VALUES(2,'Bike','Medium','>60','Bike 90 min as 45 min steady, 4 x (5 min Hard, 3 min easy), 13 min steady');
INSERT INTO "workoutTbl" VALUES(3,'Bike','Hard','>60','After a full warm up, do a long ride in zone 2. Try to find a hilly route to ride to continue to build leg strength and overall endurance. You will push in to zone 3-4 for hill climbing. Maintain an average cadence of 85-100 rpms throughout the entire workout. Cool down in zones 1-2.');
INSERT INTO "workoutTbl" VALUES(4,'Bike','Easy','30-60','bike-starting steady, building to up-tempo');
INSERT INTO "workoutTbl" VALUES(5,'Bike','Medium','30-60','Bike-easy with 3 x 30 second accelerations');
INSERT INTO "workoutTbl" VALUES(6,'Bike','Easy','<30','bike-easy, insert 3 x 30 second spin-ups (105+rpm) at light resistance');
INSERT INTO "workoutTbl" VALUES(7,'Bike','Hard','30-60','WU:Spin for 10 minutes in Zone 1MS: Ride for 30 minutes in Zone 2. During this time shift down to a big gear that you can only turn 70 rpm with medium hard effort, and ride at that effort for 5 intervals of 2 minutes.CD:Spin for remainder of the ride in Zone 1');
INSERT INTO "workoutTbl" VALUES(8,'Bike','Medium','30-60','WU: 10 minutes easy spinning in Zone 1.MS: Un-clip right leg, and pedal with left leg only for 45 seconds. Then, un-clip left leg, and pedal with right leg only for 45 seconds. Follwing this pedal with both legs for 30 seconds. Repeat this cycle 5 times. CD: Spin easily in Zone 1 for remainder of the ride.');
INSERT INTO "workoutTbl" VALUES(9,'Bike','Hard','<30','WU:Spin for 10 minutes in Zone 1MS: 6 x 4 minutes in the big ring with a low gear in the back 5315 or so. The cadence can be low; this is a strength building routine. RI: 2 minutes.CD:Spin for remainder of the ride in Zone 1');
INSERT INTO "workoutTbl" VALUES(10,'Bike','Medium','<30','bike-easy, insert 3 x 30 second spin-ups (105+rpm) at medium resistance');
INSERT INTO "workoutTbl" VALUES(11,'Run','Hard','<30','WU: Run for 10 minutes in Zone 12 building to high Zone 2. During this time complete 4-30 second efforts at slightly slower than 10k pace.MS: Run for 15 minutes at 10 beats below LTHRCD: Run for 5 minutes in Zone 1');
INSERT INTO "workoutTbl" VALUES(12,'Run','Easy','<30','Run easily in zone 1. Try to maintain pace of 22 left foot strikes in 15 seconds.');
INSERT INTO "workoutTbl" VALUES(13,'Run','Medium','<30','WU: Easy Zone 1 run for 15 minutes.MS: 5x20 seconds fast on soft, gentle downhill. Approximately 400m race pace. Not all out. Relax. Walk and hop back to start point during each recovery. Hop 30 times on right leg and then 30 times on left leg (hops are to build footleg strength). CD: Easy Zone 1 run for the remainder of the workout.');
INSERT INTO "workoutTbl" VALUES(14,'Run','Hard','30-60','WU: Run in Zone 1 for 10 minutesMS: Run at a pace bordering on uncomfortable for 30 minutes.CD: Run in Zone 1 for the remainder of the workout.');
INSERT INTO "workoutTbl" VALUES(15,'Run','Easy','30-60','Run easily in zone 1. Try to maintain pace of 22 left foot strikes in 15 seconds.');
INSERT INTO "workoutTbl" VALUES(16,'Run','Easy','>60','WU:Run in Zone 1 for 15 minutesMS:Stay in zone 2 focusing on form. Run at this pace for 40 minutes.CD:Hit lap button at conclusion of main set, and cool down in Zone 1 for the remainder of the workout.');
INSERT INTO "workoutTbl" VALUES(17,'Run','Medium','30-60','Try to do this on grass.WU: 10 minute Zone 1 run.MS: 8 x 30 left-foot steps. Goal = 19-20 seconds. On the recoveries skip 60 times (30 skips each leg alternating). Include walking in recoveries. Perfect form! CD: Zone 1 run for remainder of the workout.');
INSERT INTO "workoutTbl" VALUES(18,'Run','Medium','>60','WU:Run in Zone 1 for 10 minutesMS:Hit lap button after warm up and steadily raise HR to Zone 3. Run at this pace for 30 minutes.CD:Hit lap button at conclusion of main set, and cool down in Zone 1 for the remainder of the workout.');
INSERT INTO "workoutTbl" VALUES(19,'Run','Hard','>60','WU: Run in Zone 1 moving up to Zone 2 for 15 minutesMS: Slowly increase pace to a level that borders on the uncomfortable. Keep rhythm and stay at this effort level for 30 minutes. If you need to begin to back off, do that. You can also increase pace to maintain your level of perceived exertion.CD: Run easily in Zone 1 for the remainder of the run.');
INSERT INTO "workoutTbl" VALUES(20,'Swim','Easy','<30','swim-15 min easy with 3 x 30 second accelerations');
INSERT INTO "workoutTbl" VALUES(21,'Swim','Medium','<30','2000 yards with short, hard intervals');
INSERT INTO "workoutTbl" VALUES(22,'Swim','Hard <30','<30','3 x 25 all out (RI :20) 25 drill. Repeat this sequence 8 times.');
INSERT INTO "workoutTbl" VALUES(23,'Swim','Easy','30-60','WU: 6 x 50 done as 25 scull and 25 distance per stroke. Then 4 x 50 done as 25 swim and 25 drill.MS: On each even interval of the set count strokes, focusing on form. On the alternate 25s increase speed slightly. Recoveries are indicated in seconds within parentheses. 8 x 100 (30?) at aerobic effort (well below T-pace).2 x 50 kick (15?) moderate effort.CD: 300 easy swim.');
INSERT INTO "workoutTbl" VALUES(24,'Swim','Medium','30-60','WU: 300 Swim, 100 kick, 100 pull3 x (200 moderate (RI: :20)4 x 75 Fast (RI: :15))200 done as 2 x (25 kick hard, 25 kick easy 25 swim hard 25 swim easy.)CD: 300 easy swim');
INSERT INTO "workoutTbl" VALUES(25,'Swim','Hard','30-60','WU: 200 easy swim, 4 X 50 done as 25 drill, 25 perfect form.(RI :20)MS: 12 x 25 sprint (RI :30), 	2 x 100 IM (:RI 30), 6 x 50 sprint (RI :30), 100 easy, 100 fast RI (:30)CD: 200 easy swim, 50 kick, 50 pull.');
INSERT INTO "workoutTbl" VALUES(26,'Swim','Easy','>60','WU: 6 x 50 increasing pace slightly each 50.MS: Swim 4 x 500. The first one should be: (100 moderate, 100 fast, 100 easy 100 moderate 100 easy). The second: (100 easy, 100 moderate, 100 fast 100 easy 100 moderate). The third: (100 fast, 100 moderate, 100 fast 100 easy 100 fast). The fourth: (100 easy, 100 moderate, 100 easy 100 moderate 100 easy). Rest :30 between each 500.CD: 50 kick, 200 easy with emphasis on form, 50 pull.');
INSERT INTO "workoutTbl" VALUES(27,'Swim','Medium','>60','Workout (2,100 yards)Warm up: 300 (100 swim100 pull100 kick)Drill set: 4 x 100 (50 drill50 swim - drill is one-arm free; alternate leftright on each 25) Main set: 1 x 400 even paced2 x 200 (50 swim100 kick50 swim)3 x 100 even paced4 x 50 (odds easyevens strong)Cool down: 100 swim');
INSERT INTO "workoutTbl" VALUES(28,'Swim','Hard','>60','Warm up: 200 swim100 kick200 pullDrill Set: 6 x 50 drillswim by 25Pre Set: 6 x 50 of 25 fast25 easy, rest 15 secMain set: 200 meters as fast as you can go from a push start, try to keep your stroke long and strong. Record your time.one minute recovery between sets800 meters from a push start, as fast as you can go. Try to remember to focus on the back half of your stroke as well as staying as streamlined as possible in the water. Record your time.');
