DROP TABLE IF EXISTS "workoutTbl";
CREATE TABLE "workoutTbl" ("col_1" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "col_2" VARCHAR, "col_3" VARCHAR, "col_4" VARCHAR, "col_5" VARCHAR);
INSERT INTO "workoutTbl" VALUES(1,'Bike','Easy','>60','bike 115 min steady and 35 min up-tempo');
INSERT INTO "workoutTbl" VALUES(2,'Bike','Medium','>60','Bike 90 min as 45 min steady, 4 x (5 min Hard, 3 min easy), 13 min steady');
INSERT INTO "workoutTbl" VALUES(3,'Bike','Hard','>60','After a full warm up, do a long ride in zone 2. Try to find a hilly route to ride to continue to build leg strength and overall endurance. You will push in to zone 3-4 for hill climbing. Maintain an average cadence of 85-100 rpms throughout the entire workout. Cool down in zones 1-2.');
INSERT INTO "workoutTbl" VALUES(4,'Bike','Easy','30-60','bike-starting steady, building to up-tempo');
INSERT INTO "workoutTbl" VALUES(5,'Bike','Medium','30-60','Bike-easy with 3 x 30 second accelerations');
INSERT INTO "workoutTbl" VALUES(6,'Bike','Easy','<30','bike-easy, insert 3 x 30 second spin-ups (105+rpm) at light resistance');
INSERT INTO "workoutTbl" VALUES(7,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(8,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(9,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(10,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(11,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(12,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(13,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(14,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(15,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(16,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(17,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(18,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(19,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(20,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(21,NULL,NULL,NULL,NULL);
INSERT INTO "workoutTbl" VALUES(22,NULL,NULL,NULL,'');
